/* eslint-disable react/prop-types */
/* eslint-disable react/no-unescaped-entities */
import { Link } from "react-router-dom";
import Framework from "../../../components/CommonComponent/Framework";
import { Web3WalletFramework } from "../../../components/data/frameworkData";
import Faq from "../../../components/resuableComponent/Faq";
import { Web3WalletExchangeFaq } from "../../../components/data/faqsData";
import accessImg from "../../../assets/payment.png";
import bgimg from "../../../assets/bitcoin-key-wallet.svg";

const benefits = [
  [
    {
      image: accessImg,
      title: "Transaction Fee",
      points: "Transaction fees are an integral component of the revenue generation model. As the name indicates, a fixed or varying fee would be levied based on the transaction value. The more wallet transactions, the more revenue streams would be generated by the wallets."
    },
    {
      image: accessImg,
      title: "Swapping Fees",
      points: "Transaction fees are an integral component of the revenue generation model. As the name indicates, a fixed or varying fee would be levied based on the transaction value. The more wallet transactions, the more revenue streams would be generated by the wallets."
    },
  ],
  [
    {
      image: accessImg,
      title: "DeFi Integration",
      points: "Transaction fees are an integral component of the revenue generation model. As the name indicates, a fixed or varying fee would be levied based on the transaction value. The more wallet transactions, the more revenue streams would be generated by the wallets."
    },
    {
      image: accessImg,
      title: "Trading Fees",
      points: "Transaction fees are an integral component of the revenue generation model. As the name indicates, a fixed or varying fee would be levied based on the transaction value. The more wallet transactions, the more revenue streams would be generated by the wallets."
    },
  ],
];

const BenefitCard = ({ image, title, points }) => {
  return (
    <div className="border-[1px] border-white border-opacity-20 rounded-xl py-8  flex flex-col justify-center w-full 
    md:w-[50%] lg:w-[50%] hover:bg-greish-gradient px-4 lg:px-6">
      <img src={image} alt={title} className="w-12 lg:w-16" />
      <p className="text-white pt-4 text-lg md:text-xl font-bold">{title}</p>
      <p className="text-white text-opacity-70 text-[12px] lg:text-[15px] pt-4">{ points}</p>
    </div>
  );
};

const Web3Wallet = () => {

  return (
    <div className="mt-20 mb-20 ">
      {/* CRYPTO CURRENCY DIGITAL WALLET DEVELOPMENT COMPANY */}
      <div className="flex flex-col items-center justify-center px-4 md:px-8 lg:px-12 xl:px-36 2xl:px-32 3xl:px-60 relative">
        <div className="hidden md:block spotlightOrange spotlightOrange-left"></div>
        <div className="hidden md:block spotlight spotlight-left"></div>
        <div className="hidden md:block spotlight2 spotlight-right"></div>
        <p className="text-5xl text-white font-semibold text-center">
          Web3 Wallet <br />
          <span className="text-transparent bg-clip-text bg-green-gradient">
            Development Company
          </span>
        </p>
        <div className="flex flex-row w-full mt-12">
          <div className="w-[50%]">{/* image */}</div>
          <div className="w-[50%]">
            <p className="text-white text-opacity-70 text-justify hyphens-auto">
              A white paper is an authoritative, persuasive, and comprehensive
              document that outlines a business project’s challenges and
              solutions. It plays a crucial role in establishing industry
              authority, enhancing credibility, and demonstrating thought
              leadership. In the crypto market, a well-researched white paper
              serves as a powerful tool to attract investors and showcase your
              project’s potential.
              <br /> <br />
              At Giichi IT Solution, we specialize in crafting impactful white
              papers that combine in-depth research, solution architecture, and
              token economics. Our expert writers collaborate with industry
              professionals to develop detailed, data-driven white papers that
              add credibility and authenticity to your project.
            </p>

            {/* button to connect on whatsapp */}
            <div className="flex flex-row items-center space-x-6">
              <a
                type="button"
                href="https://wa.me/9266416198"
                target="_blank"
                rel="noopener noreferrer"
                className="mt-6 bg-green-gradient focus:outline-none cursor-pointer shadow-inner shadow-[#d4dfd1] px-6 lg:px-8 py-3 text-white  text-lg text-nowrap transform hover:scale-105 transition-transform duration-300"
                aria-label="Contact us "
                title="Click to contact us form"
              >
                Connect on Whatsapp
              </a>
              <Link to="/contact-us">
                <button
                  type="button"
                  className="mt-6 bg-green-gradient focus:outline-none cursor-pointer shadow-inner shadow-[#d4dfd1] px-6 lg:px-8 py-3 text-white  text-lg text-nowrap transform hover:scale-105 transition-transform duration-300"
                  aria-label="Contact us "
                  title="Click to contact us form"
                >
                  Request a Free Demo
                </button>
              </Link>
            </div>
          </div>
        </div>
      </div>

      {/* Our blockchain consulting related services */}
      <div className="flex flex-col lg:flex-row justify-between items-start space-x-32 w-full px-4 md:px-8 lg:px-12 xl:px-36 2xl:px-32 3xl:px-60 mt-12 md:mt-24 2xl:mt-32 mb-6 md:mb-12">
        <div className="w-full lg:w-[50%] relative">
          <div className="hidden md:block spotlight spotlight-left"></div>
          <div className="hidden md:block spotlight2 spotlight-right"></div>
          <p className="text-white text-xl md:text-2xl xl:text-3xl 2xl:text-4xl font-semibold pt-4  tracking-tight">
           What's unique About Web3 Wallet?
          </p>
          <p className="text-sm lg:text-[14px] 2xl:text-[16px] font-normal text-white text-opacity-50 pt-6 leading-6 text-justify hyphens-auto">
            Lorem ipsum dolor sit amet consectetur adipisicing elit.
            Repellendus, in consequuntur quaerat enim vitae sed, odit culpa nisi
            incidunt distinctio autem, assumenda iure aspernatur harum suscipit
            sint voluptatem quis vero facere doloribus quasi repudiandae
            perferendis nulla! Accusantium voluptas tempore libero. <br />{" "}
            <br />
            Lorem ipsum dolor sit amet consectetur adipisicing elit.
            Repellendus, in consequuntur quaerat enim vitae sed, odit culpa nisi
            incidunt distinctio autem, assumenda iure aspernatur harum suscipit
            sint voluptatem quis vero facere doloribus quasi repudiandae
            perferendis nulla! Accusantium voluptas tempore libero.
          </p>
        </div>
       <div className="w-full lg:w-[50%]">

       </div>
      </div>

    {/*  Web3 Wallet Development:  */}
      <div className="mt-0 md:mt-12 relative">
        <div className="hidden md:block spotlight spotlight-left"></div>
        <div className="hidden md:block spotlight spotlight-right"></div>
        <p className="text-white text-center text-xl md:text-5xl font-bold pt-4 tracking-wide px-4 md:px-8 lg:px-12 xl:px-36 2xl:px-32 3xl:px-60">
        Web3 Wallet Development: 
          <br />
          <span className="text-transparent bg-clip-text bg-green-gradient text-xl md:text-4xl xl:text-5xl text-center">
          Remunerative Models
          </span>
        </p>
        <p className="text-sm lg:text-[16px] font-normal text-white text-opacity-50 pt-6 px-0 xl:px-28 leading-6 text-center">
          Blockchain technology is reshaping the education sector by enhancing
          security, accessibility, credibility, and transparency.
        </p>
        <div className="px-4 md:px-8 lg:px-12 xl:px-20 3xl:px-60 pt-10">
          {benefits.map((row, rowIndex) => (
            <div
              key={rowIndex}
              className="flex flex-col md:flex-row justify-center w-full space-x-0 md:space-x-6 lg:space-x-8 space-y-4 md:space-y-0 mt-4 md:mt-6 lg:mt-8"
            >
              {row.map((benefit, index) => (
                <BenefitCard
                  key={index}
                  image={benefit.image}
                  title={benefit.title}
                  points={benefit.points}
                />
              ))}
            </div>
          ))}
        </div>
      </div>

{/* DIGITAL WALLET DEVELOPMENT SERVICES */}
      <div className="mt-20">
        <Framework
          data={Web3WalletFramework}
          heading1="Web3 Wallet"
          heading2="Development Services"
          desc="Here are a few amazing benefits that your business can get from our top blockchain consultants."
        />
      </div>

      {/* web3 crypto  wallet offerings */}
      <div className="bg-[#283430] bg-opacity-20  flex flex-row items-center space-x-32 px-4 md:px-8 lg:px-12 xl:px-36 2xl:px-32 3xl:px-60 mt-20 mb-20 p-10">
        <div>  <img src={bgimg} alt="" className=""/></div>
        <div>
        <p className="text-white text-2xl font-semibold w-[80%]">Offer an Exhilarating User Experience with Our Web3 Crypto Wallet Solutions</p>
        <Link to="/contact-us">
                <button
                  type="button"
                  className="mt-6 bg-green-gradient focus:outline-none cursor-pointer shadow-inner shadow-[#d4dfd1] px-6 lg:px-8 py-3 text-white  text-lg text-nowrap transform hover:scale-105 transition-transform duration-300"
                  aria-label="Contact us "
                  title="Click to contact us form"
                >
                  Request a Free Demo
                </button>
              </Link>
        </div>
      </div>

      {/* Features offered by Supply Chain Management */}
            <div className="mb-6 xl:mb-12 2xl:mb-24 mt-24">
              <p className="text-white text-xl md:text-2xl lg:text-3xl xl:text-4xl 2xl:text-5xl font-bold text-center pt-4 leading-tight tracking-wide px-4 md:px-8 lg:px-12 xl:px-36 2xl:text-32 3xl:px-60 ">
              Our Unique Offerings in <br />
                <span className="block pt-2 text-transparent bg-clip-text bg-green-gradient">
                Web3 Wallet
                </span>
              </p>
              <div className="flex flex-col justify-center items-center">
              <p className="block text-sm md:text-[17px] lg:text-[15px] 2xl:text-[17px] text-white text-opacity-70 pt-4 px-4 w-full md:w-[50%] leading-7 text-center">
                Our blockchain supply chain solutions are packed with user-friendly, advanced features that empower businesses to efficiently manage their supply chain operations without hassle.
              </p>
              </div>
              <div className="flex flex-col md:flex-row justify-between space-x-0 md:space-x-4 2xl:space-x-8 px-4 md:px-8 lg:px-12 xl:px-36 2xl:px-32 3xl:px-60 pt-12">
                <div className="border-[1px] border-white border-opacity-20 rounded-xl h-[240px] py-12 flex flex-col justify-center items-center w-full md:w-[20%] group relative ">
                  <img src={accessImg} alt="report-image" className="w-16 group-hover:hidden" />
                  <p className="text-white font-semibold pt-4 text-center group-hover:hidden text-[15px] 2xl:text-[17px]">
                  Cost-effective wallet creation
                  </p>
                  <p
                    className=" text-white text-opacity-70 pt-4 text-sm md:text-[8px] lg:text-xs 2xl:text-sm opacity-0 translate-y-8 group-hover:opacity-100 group-hover:translate-y-0 transition-all duration-700 ease-in-out delay-100 absolute 
                     bottom-12 md:bottom-8 p-4 md:p-2 lg:md:p-4 left-0 right-0 text-center "
                  >
                    A comprehensive dashboard that provides real-time insights and
                    detailed analytics for better decision-making and enhanced
                    visibility across supply chain processes.
                  </p>
                </div>
      
                <div className="mt-4 md:mt-0 border-[1px] border-white border-opacity-20 rounded-xl h-[240px] py-12 flex flex-col justify-center items-center w-full md:w-[20%] group relative ">
                  <img src={accessImg} alt="manage-image" className="w-16 group-hover:hidden" />
                  <p className="text-white font-semibold pt-4 text-center group-hover:hidden  text-[15px] 2xl:text-[17px]">
                  Technical expertise
                  </p>
                  <p
                    className=" text-white text-opacity-70 pt-4 text-sm md:text-[8px] lg:text-xs 2xl:text-sm opacity-0 translate-y-8 group-hover:opacity-100 group-hover:translate-y-0 transition-all duration-700 ease-in-out delay-100 absolute 
                      bottom-12 md:bottom-8 left-0 right-0 text-center p-4 md:p-2 lg:md:p-4"
                  >
                    Streamline user access and roles within the supply chain network
                    with robust management tools, ensuring secure and controlled
                    interactions.
                  </p>
                </div>
      
                <div className="mt-4 md:mt-0 border-[1px] border-white border-opacity-20 rounded-xl h-[240px] py-12 flex flex-col justify-center items-center w-full md:w-[20%] group relative ">
                  <img src={accessImg} alt="wallet-image" className="w-16 group-hover:hidden" />
                  <p className="text-white font-semibold pt-4 text-center group-hover:hidden  text-[15px] 2xl:text-[17px]">
                  Flexible models
                  </p>
                  <p
                    className=" text-white text-opacity-70 pt-4 text-sm md:text-[8px] lg:text-xs 2xl:text-sm opacity-0 translate-y-8 group-hover:opacity-100 group-hover:translate-y-0 transition-all duration-700 ease-in-out delay-100 absolute 
                      bottom-12 md:bottom-8 left-0 right-0 text-center p-4 md:p-2 lg:md:p-4"
                  >
                    A versatile wallet that supports multiple currencies, enabling
                    businesses to manage and process transactions seamlessly in
                    various currencies within the supply chain ecosystem.
                  </p>
                </div>
      
                <div className="mt-4 md:mt-0 border-[1px] border-white border-opacity-20 rounded-xl h-[240px] py-12 flex flex-col justify-center items-center w-full md:w-[20%] group relative ">
                  <img src={accessImg} alt="know-your-customer-image" className="w-16 group-hover:hidden" />
                  <p className="text-white font-semibold pt-4 text-center group-hover:hidden  text-[15px] 2xl:text-[17px]">
                  Transparent pricing
                  </p>
                  <p
                    className=" text-white text-opacity-70 pt-4 text-sm md:text-[8px] lg:text-xs 2xl:text-sm opacity-0 translate-y-8 group-hover:opacity-100 group-hover:translate-y-0 transition-all duration-700 ease-in-out delay-100 absolute 
                      bottom-12 md:bottom-8 left-0 right-0 text-center p-4 md:p-2 lg:md:p-4"
                  >
                    Integrated Know Your Customer (KYC) and Anti-Money Laundering
                    (AML) features ensure compliance and secure onboarding of supply
                    chain participants, while simplifying verification processes.
                  </p>
                </div>
      
                <div className="mt-4 md:mt-0 border-[1px] border-white border-opacity-20 rounded-xl h-[240px] py-12 flex flex-col justify-center items-center w-full md:w-[20%] group relative ">
                  <img src={accessImg} alt="funding-icon" className="w-16 group-hover:hidden" />
                  <p className="text-white font-semibold pt-4 text-center group-hover:hidden text-[15px] 2xl:text-[17px]">
                  24/7 customer assistance
                  </p>
                  <p
                    className=" text-white text-opacity-70 pt-4 text-sm md:text-[8px] lg:text-xs 2xl:text-sm opacity-0 translate-y-8 group-hover:opacity-100 group-hover:translate-y-0 transition-all duration-700 ease-in-out delay-100 absolute 
                      bottom-12 md:bottom-8 left-0 right-0 text-center p-4 md:p-2 lg:md:p-4"
                  >
                    A powerful system for managing funds with real-time tracking of
                    total supply, funds in circulation, and more, offering businesses
                    complete control over financial operations.
                  </p>
                </div>
              </div>
            </div>

      {/* FAQ SECTION */}
      <div>
        <Faq data={Web3WalletExchangeFaq} />
      </div>
    </div>
  );
};

export default Web3Wallet;
